name: Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use the Node.js version your app requires
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx ng build --prod  # Builds your app; adjust flags as needed
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3  # Updated from v1 to v3
        with:
          path: dist/memolibre  # Replace with your app’s output folder
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
